// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_URL = "https://eossaxfosnmtjksefekk.supabase.co";
const DEFAULT_PUBLISHABLE_KEY = "sb_publishable_2fOzpgED10xOerEYIN7WRg_vrpvCC6M";

// Try multiple env keys (Vite and Next style)
const envs: Record<string, any> = (import.meta as any).env || {};
let resolvedUrl: string | undefined =
  envs.VITE_SUPABASE_URL ||
  envs.NEXT_PUBLIC_SUPABASE_URL ||
  undefined;
let resolvedKey: string | undefined =
  envs.VITE_SUPABASE_PUBLISHABLE_KEY ||
  envs.VITE_SUPABASE_ANON_KEY ||
  envs.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  envs.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY ||
  undefined;
try {
  if (typeof window !== 'undefined') {
    const lsUrl = localStorage.getItem('SUPABASE_URL') || undefined;
    const lsKey = localStorage.getItem('SUPABASE_PUBLISHABLE_KEY') || undefined;
    resolvedUrl = lsUrl || resolvedUrl;
    resolvedKey = lsKey || resolvedKey;
  }
} catch {
  void 0;
}

if (!resolvedUrl || !resolvedKey) {
  console.warn("Supabase não configurado. Usando defaults fornecidos.");
}

export let supabase = createClient<Database>(
  resolvedUrl || DEFAULT_URL,
  resolvedKey || DEFAULT_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

export function setSupabaseConfig(url: string, key: string) {
  try {
    if (typeof window !== 'undefined') {
      localStorage.setItem('SUPABASE_URL', url);
      localStorage.setItem('SUPABASE_PUBLISHABLE_KEY', key);
    }
  } catch {
    void 0;
  }
  supabase = createClient<Database>(url, key, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export function getSupabaseStatus() {
  const envs: Record<string, any> = (import.meta as any).env || {};
  let envUrl =
    envs.VITE_SUPABASE_URL ||
    envs.NEXT_PUBLIC_SUPABASE_URL ||
    undefined;
  let envKey =
    envs.VITE_SUPABASE_PUBLISHABLE_KEY ||
    envs.VITE_SUPABASE_ANON_KEY ||
    envs.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
    envs.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY ||
    undefined;
  let lsUrl: string | null = null;
  let lsKey: string | null = null;
  try {
    if (typeof window !== 'undefined') {
      lsUrl = localStorage.getItem('SUPABASE_URL');
      lsKey = localStorage.getItem('SUPABASE_PUBLISHABLE_KEY');
    }
  } catch {
    void 0;
  }
  const currentUrl = resolvedUrl || lsUrl || envUrl || DEFAULT_URL;
  const currentKey = resolvedKey || lsKey || envKey || DEFAULT_PUBLISHABLE_KEY;
  return {
    envConfigured: !!(envUrl && envKey),
    localConfigured: !!(lsUrl && lsKey),
    usingPlaceholder: currentUrl === DEFAULT_URL && currentKey === DEFAULT_PUBLISHABLE_KEY,
    url: currentUrl,
  };
}
