// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_URL = "https://eossaxfosnmtjksefekk.supabase.co";
const DEFAULT_PUBLISHABLE_KEY = "sb_publishable_2fOzpgED10xOerEYIN7WRg_vrpvCC6M";

function sanitizeSupabaseUrl(input: string): string {
  const s = String(input || "").trim();
  const m = s.match(/supabase\.com\/dashboard\/project\/([a-zA-Z0-9-]+)/);
  if (m) return `https://${m[1]}.supabase.co`;
  return s;
}

// Try multiple env keys (Vite and Next style)
const envs: Record<string, any> = (import.meta as any).env || {};
let resolvedUrl: string | undefined =
  sanitizeSupabaseUrl(envs.VITE_SUPABASE_URL || envs.NEXT_PUBLIC_SUPABASE_URL || "") ||
  undefined;
let resolvedKey: string | undefined =
  envs.VITE_SUPABASE_PUBLISHABLE_KEY ||
  envs.VITE_SUPABASE_ANON_KEY ||
  envs.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
  envs.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY ||
  undefined;
try {
  if (typeof window !== 'undefined') {
    const lsUrl = sanitizeSupabaseUrl(localStorage.getItem('SUPABASE_URL') || "");
    const lsKey = localStorage.getItem('SUPABASE_PUBLISHABLE_KEY') || undefined;
    resolvedUrl = lsUrl || resolvedUrl;
    resolvedKey = lsKey || resolvedKey;
  }
} catch {
  void 0;
}

if (!resolvedUrl || !resolvedKey) {
  console.warn("Supabase não configurado. Usando defaults fornecidos.");
}

export let supabase = createClient<Database>(
  sanitizeSupabaseUrl(resolvedUrl || DEFAULT_URL),
  resolvedKey || DEFAULT_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

export function setSupabaseConfig(url: string, key: string) {
  try {
    if (typeof window !== 'undefined') {
      localStorage.setItem('SUPABASE_URL', sanitizeSupabaseUrl(url));
      localStorage.setItem('SUPABASE_PUBLISHABLE_KEY', key);
    }
  } catch {
    void 0;
  }
  resolvedUrl = sanitizeSupabaseUrl(url);
  resolvedKey = key;
  supabase = createClient<Database>(resolvedUrl, resolvedKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export function getSupabaseStatus() {
  const envs: Record<string, any> = (import.meta as any).env || {};
  let envUrl =
    sanitizeSupabaseUrl(envs.VITE_SUPABASE_URL || envs.NEXT_PUBLIC_SUPABASE_URL || "") ||
    undefined;
  let envKey =
    envs.VITE_SUPABASE_PUBLISHABLE_KEY ||
    envs.VITE_SUPABASE_ANON_KEY ||
    envs.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ||
    envs.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY ||
    undefined;
  let lsUrl: string | null = null;
  let lsKey: string | null = null;
  try {
    if (typeof window !== 'undefined') {
      lsUrl = sanitizeSupabaseUrl(localStorage.getItem('SUPABASE_URL') || "");
      lsKey = localStorage.getItem('SUPABASE_PUBLISHABLE_KEY');
    }
  } catch {
    void 0;
  }
  const currentUrl = lsUrl || envUrl || resolvedUrl || DEFAULT_URL;
  const currentKey = lsKey || envKey || resolvedKey || DEFAULT_PUBLISHABLE_KEY;
  return {
    envConfigured: !!(envUrl && envKey),
    localConfigured: !!(lsUrl && lsKey),
    usingPlaceholder: currentUrl === DEFAULT_URL && currentKey === DEFAULT_PUBLISHABLE_KEY,
    url: currentUrl,
  };
}
